dist: xenial
language: node_js
cache: npm

env:
    global:
        - SCRIPT_ARGS=$(if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "--since $TRAVIS_BRANCH"; else echo ""; fi)

jobs:
    include:
        - name: "TEST env vars"
          install: skip
          script:
              - echo $SCRIPT_ARGS
        - name: "Lint"
          script: npm run lint -- $SCRIPT_ARGS
        - name: "Build"
          script: npm run build -- $SCRIPT_ARGS
        - name: "Unit tests"
          script: npm test -- $SCRIPT_ARGS
