dist: xenial
language: node_js
cache: npm

env:
    global:
        - CHANGED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep -v "^packages")
        - PARTIAL_BUILD=$([ "$CHANGED_FILES" == "" ] && [ "$TRAVIS_PULL_REQUEST" == "true" ])
        - SCRIPT_ARGS=$(if [ "$PARTIAL_BUILD" = "true" ]; then echo "--since $TRAVIS_BRANCH"; else echo ""; fi)

jobs:
    include:
        - name: "TEST env vars"
          script:
              - echo $CHANGED_FILES
              - echo $PARTIAL_BUILD
              - echo $SCRIPT_ARGS
        - name: "Lint"
          script: npm run lint -- $SCRIPT_ARGS
        - name: "Build"
          script: npm run build -- $SCRIPT_ARGS
        - name: "Unit tests"
          script: npm test -- $SCRIPT_ARGS
